- hosts: all
  #Specify remote_user and sudo if running as sudo user
  remote_user: adithya
  sudo: yes

  tasks:
  - name: Health check
    shell: curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
    register: health

  - debug: var=health.stdout_lines