- name: Add the elasticsearch APT repository key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add the elasticsearch APT repository
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main" state=present

- name: Install elasticsearch
  apt: name={{ item }} state=present force=yes
  with_items:
  - elasticsearch
  notify: start elasticsearch 